version: 2
updates:

  - package-ecosystem: "npm"
    directory: "eth-pm"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
            [ "version-update:semver-patch", "version-update:semver-minor" ]

  - package-ecosystem: "npm"
    directory: "eth-pm-wallet-encryption"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
          [ "version-update:semver-patch", "version-update:semver-minor" ]

  - package-ecosystem: "npm"
    directory: "relay-angular-chat"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
          [ "version-update:semver-patch", "version-update:semver-minor" ]

  - package-ecosystem: "npm"
    directory: "relay-reactjs-chat"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
          [ "version-update:semver-patch", "version-update:semver-minor" ]

  - package-ecosystem: "npm"
    directory: "store-reactjs-chat"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
          [ "version-update:semver-patch", "version-update:semver-minor" ]

  - package-ecosystem: "npm"
    directory: "web-chat"
    schedule:
      interval: "daily"
    reviewers: [ "d4nte" ]
    ignore:
      - dependency-name: "*"
        update-types:
          [ "version-update:semver-patch", "version-update:semver-minor" ]
